name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set up Swift
      run: sudo xcode-select --switch /Applications/Xcode_14.0.app
    - name: Install Dependencies
      run: pod install
    - name: Build and Test
      run: xcodebuild -workspace DnDDiceRoller.xcworkspace -scheme DnDDiceRoller -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14 Pro,OS=16.0' clean build test
    - name: Archive Logs
      uses: actions/upload-artifact@v2
      with:
        name: logs
        path: logs

