name: Project Board Automation

on:
  issues:
    types: [opened, closed, reopened, labeled, unlabeled]
  pull_request:
    types: [opened, closed, reopened, review_requested, converted_to_draft]

jobs:
  project_automation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/ChaseWhiteRabbit/projects/dnd-dice-roller-roadmap
          github-token: ${{ secrets.PROJECT_TOKEN }}

  update_project_status:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PROJECT_TOKEN }}
          script: |
            const { issue, pull_request } = context.payload;
            const item = issue || pull_request;
            
            if (context.eventName === 'issues') {
              if (context.payload.action === 'opened') {
                // Move to Backlog
                await setProjectStatus(item.node_id, 'Backlog');
              } else if (context.payload.action === 'closed') {
                // Move to Done
                await setProjectStatus(item.node_id, 'Done');
              }
            } else if (context.eventName === 'pull_request') {
              if (context.payload.action === 'opened') {
                // Move to In Progress
                await setProjectStatus(item.node_id, 'In Progress');
              } else if (context.payload.action === 'review_requested') {
                // Move to In Review
                await setProjectStatus(item.node_id, 'In Review');
              } else if (context.payload.action === 'closed' && item.merged) {
                // Move to Done
                await setProjectStatus(item.node_id, 'Done');
              }
            }
